User registration, database connection, unit tests and more
kamwro/emobility-backend-app pull request #4
Opened 2023-11-13 07:05 UTC by kamwro

### Some features

1. Some user CRUDs: saving, reading, deleting
2. User registration logic
3. Unit tests for all services
4. Environmental variables validation (Joi)
5. Dtos, entities
6. Prettier formating

2023-11-13 11:37 UTC, krystiansoltys99 reviewed
I think the structure of the project can be simplified a little. I feel like `index.ts` which is used only to export class in almost every folder adds unnecessary complexity.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/app/controllers/app.controller.ts
> +    let url = `http://localhost:${port}/api#/` as string;
Please use `const` instead of `let`. I also think you don't need to cast types here.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/auth/controllers/auth.controller.ts
> +    await this._authService.logIn();
I guess `body` should be passed to `logIn`?

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/auth/controllers/auth.controller.ts
> +  async logOut(): Promise<any> {
Please add proper return type instead of `any`.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/auth/dtos/create-auth.dto.ts
> +  @Matches(/((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/, {
I think this regex can be moved to separate variable. Maybe you can put in somewhere in `constants.ts` so it can be easily accessed in whole project.

2023-11-13 11:37 UTC, krystiansoltys99 commented on package.json
> +    "@types/bcrypt": "^5.0.1",
I think this package should be in `devDependencies`.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/app/app.module.ts
> +import * as Joi from 'joi';
I'd suggest to use `zod` or `class-validator`.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/me/controllers/me.controller.ts
> +export class MeController {
I would rename this to something more meaningful.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/users/services/users.service.spec.ts
> +        expect(result === undefined || result === null).toEqual(false);
You can use `toBeFalsy()` method.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/users/services/users.service.ts
> +    if (typeof id !== 'number') {
Typescript will not allow you to use other type than number here so I think this check is not necessary.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/users/services/users.service.ts
> +    const user = await this.findOne((id = id));
I would call it directly from the repository - `findOneBy({ id })`.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/utils/abstracts/abstract-entity.ts
> +  public uuid: string;
I think you don't need both `id` and `uuid`. I'd suggest to remove one of them.

2023-11-13 11:37 UTC, krystiansoltys99 commented on src/utils/security/password-hash.ts
> +export class HashProvider {
I think you don't need separate class to generate hash. It can be just one simple function.

2023-11-13 12:32 UTC, kamwro commented on src/auth/controllers/auth.controller.ts
> +    await this._authService.logIn();
Will come with next PR, as it's not implemented yet

2023-11-13 12:32 UTC, kamwro commented on src/auth/controllers/auth.controller.ts
> +  async logOut(): Promise<any> {
Will come with next PR, as it's not implemented yet

2023-11-13 17:11 UTC, kamwro commented on package.json
> +    "@types/bcrypt": "^5.0.1",
Resolved with a commit

2023-11-13 17:13 UTC, kamwro commented
> I think the structure of the project can be simplified a little. I feel like `index.ts` which is used only to export class in almost every folder adds unnecessary complexity.

Thank you, I'll try my best in removing them where they are unnecessary

2023-11-13 17:14 UTC, kamwro commented on src/me/controllers/me.controller.ts
> +export class MeController {
I'll rename this module to Account

2023-11-13 17:25 UTC, kamwro commented on src/utils/abstracts/abstract-entity.ts
> +  public uuid: string;
I'll stick with incremental `id` and get rid of abstractDTO then, since it only contains uuid

2023-11-14 09:56 UTC, mwaszkiewicz requested changes

2023-11-14 09:56 UTC, mwaszkiewicz commented on Dockerfile
> +FROM node:18-alpine
Please read this article -> https://snyk.io/blog/choosing-the-best-node-js-docker-image/ and then change the base image of node.js

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/users/services/users.service.ts
> +    private readonly _usersRepository: Repository<User>,
please use native js private syntax "#" instead of TS "private"

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/users/services/users.service.ts
> +    if (typeof id !== 'number') {
id you should validate in controller at the beginning

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/users/services/users.service.ts
> +    return this._usersRepository.find();
missing await -> in that case if exception will be thrown then you will lose some of the stack trace

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/users/services/users.service.ts
> +      user = this._usersRepository.create({ ...createUserDTO, authentication });
you don't need to use query Runner to create or delete entity, you can just use "await userRepo.save or remove"

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/users/entities/user.entity.ts
> +  public address: string;
Address should be a separated entity with more complex definition

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/users/entities/user.entity.ts
> +  public authentication: Authentication;
I think that you can remove this table, due to the fact that you can have password column in the user table

2023-11-14 09:56 UTC, mwaszkiewicz commented on src/app/controllers/index.ts
> +export { AppController } from './app.controller';
index.ts files are not needed in Nest.js framework

2023-11-16 11:26 UTC, merged